users/admin.py
users/models.py

23.06.08.
users/models.py : 유저 모델 추가

Add: 유저 모델 추가 #2 #3

---

.gitignore
Realby_project/urls.py
blogs/admin.py
blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py

2023.06..09
블로그 개설, 정보불러오기
카테고리 생성, 해당게시글 불러오기
게시글 상세보기, 생성, 수정, 삭제
토픽모델 TextChoice수정

Add: Blog/Article, Category, Topic #5, #6

---

.gitignore
blogs/admin.py
blogs/models.py
blogs/serializers.py
blogs/tests.py
blogs/urls.py
blogs/views.py

2023.06.12
블로그 개설추가
카테고리 생성추가
게시글 공감추가
댓글 조회/작성/수정/삭제 추가
.gitignore 마이그레이션파일 추가

PR 23.06.12

---

Realby_project/settings.py
users/models.py
users/serializers.py
users/urls.py
users/views.py

23.06.12.
users/models.py : subscribes 변수 추가
users/serializers.py : UserSubscribeSerializer 추가
users/views.py : SubscribeView 추가 ( 구독 기능 )

Add: users/modelds, serializers, views 기능 추가 #8

---

blogs/models.py
blogs/serializers.py

2023.06.12
blogs/models.py - Topic수정
serializers.py - 포매터에 의한 수정

Edit: blogs/models.py, serializers.py #5 PR

---

blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py
users/serializers.py
users/tokens.py
users/urls.py
users/views.py

23.06.12
blogs/models.py 수정
blogs/serializers.py 수정
blogs/urls.py 수정

Fix: blog앱 오류 수정

---

blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py
users/views.py

23.06.13.
blogs/models.py : subscribes 변수 추가
blogs/serializers.py : 자잘한 serializer 변경, BlogsubscribeSerializer 추가
blogs/views.py : MainView 추가, SubscribeView 추가,
ArticleDetailView(조회수) 추가

Add: 구독기능, 메인페이지 조회수별로 나열하기 기능 추가 #8 #6 #5 #1

---

blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py
users/models.py

23.06.13.
blogs/urls.py : <int:blog_id>를 <str:blog_name>으로 전부 수정 blogs/views.py : blog_id를 받는것을 blog_name으로 받게 수정

Refact: blogs/urls.py의 url 수정 및 그에따른 view함수 수정

---

blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py

23.06.14.
blogs/models.py : TopicChoices클래스 수정, topic 변수 수정
blogs/serializers.py : category 부분 수정
blogs/views.py : SubscribeView의 post부분 수정, CategoryView의 카테고리 생성&삭제 기능 추가

Add: blogs/models.py serializers.py urls.py 수정, 카테고리 생성&삭제 기능 추가, 구독기능 수정 #5, #6, #8

---

Realby_project/settings.py
Realby_project/urls.py
users/models.py
users/tokens.py
users/urls.py
users/views.py

23.06.14.
Realby_project/settings.py : 이메일 인증 코드 추가
secrets.json : 이메일 인증용 호스트 정보 추가
users/models.py : 필드 값 수정
users/view.py : 이메일 인증 및 프로필 관련 오류 수정
ssage for your changes. Lines starting

Fix: 유저 앱 버그 수정 #2 #3

---

blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py

23.06.14.
blogs
/models.py : ReComment 모델 추가
/serializers.py : ReCommentSerializer 추가 및 CommentSerializer 수정 /urls.py : 대댓글 url 추가
/views.py ReCommentView 추가

Add: 대댓글 기능 추가 #7

---

blogs/urls.py
blogs/views.py

2023.06.14
블로그 리스트불러오기 추가
blogs/views.py, urls.py

Add: Blog LIst  #4

---

blogs/models.py
blogs/pagination.py
blogs/urls.py
blogs/views.py

23.06.16.
blogs/
pagination.py : PaginationMixin 클래스 추가
views.py : ArticlePagination 클래스  추가 및 ArticleView 클래스 수정

Add: pagination 기능 추가 #1 #5

---

blogs/models.py
blogs/pagination.py
blogs/serializers.py
blogs/urls.py
blogs/views.py

23.06.16.
blogs/
models.py : class Article에 empathys 추가, class ArticleEmpathys 추가 serializers.py : class  ArticleEmpathySerializer 추가 views.py : class ArticleEmpathyView 추가

Add: 공감 기능 추가 #8

---

blogs/serializers.py
blogs/urls.py
blogs/views.py

23.06.19.
blogs/
views.py : SearchView 추가. SubscribeView 수정

Add & Fix: 게시글 검색기능 추가 및 구독 오류 수정 #5 #8

---

Realby_project/settings.py
Realby_project/urls.py
poetry.lock
pyproject.toml
users/models.py
users/serializers.py
users/urls.py
users/views.py

23.06.17.
users/urls.py : 소셜 로그인 경로 추가
users/view.py : 소셜 로그인 클래스 추가

Add: 소셜 로그인 기능 추가 #2

---

Realby_project/settings.py

23.06.20.
Realby_project/settings.py : mysql로 db 설정 수정

Build: mysql db 연결

---

blogs/models.py
blogs/serializers.py
blogs/urls.py
blogs/views.py

2023.06.20
게시글모델의 카테고리, 토픽 속성수정
대댓글 작성/불러오기/수정/삭제 함수수정 및 정리
대댓글 url연결 수정
대댓글 기본 직렬화수정
+
HOTFIX커밋추가

Add, Fix: ReComment, Article/Category, Topic #6, #7

---

users/serializers.py
users/urls.py
users/views.py

23.06.29.
users/serializers.py
users/urls.py
users/views.py

Add: 일반 회원가입, 로그인, 로그아웃 및 JWT인증 관련 수정

---

users/models.py
users/social.py
users/urls.py
users/views.py

23.07.03.
users/urls.py : 소셜로그인 관련 라우팅 수정
users/social.py : 소셜로그인(카카오) 기능 추가

Add: 소셜로그인(카카오) 기능 추가

---

Realby_project/settings.py
backoffice/models.py
backoffice/serializers.py
backoffice/urls.py
backoffice/views.py
blogs/models.py
blogs/serializers.py
blogs/views.py
livechat/consumers.py
livechat/models.py

23.07.03.
backoffice/views.py : BackArticleHitView, BackArticleEmpathyView 추가 
backoffice/serializers.py : BackArticleSerializer 추가

Add: backoffice view, urls, serializer 추가 #52

---

Realby_project/settings.py
pyproject.toml
users/serializers.py
users/social.py

HotFix: settings 안의 주소 변경

---

Realby_project/settings.py

23.07.05.
settings.py : local주소로 변경 및 핫픽스

HotFix: 개발을 위한 local주소 변경

---

Realby_project/settings.py
users/models.py
users/serializers.py
users/social.py
users/urls.py
users/views.py

2023.07.09
쿠키관련 코드추가
카카오 로그아웃 함수추가

Add: Kakao Logout, cookie
